#ifndef _CONSTANT_H
#define _CONSTANT_H
#define FEATURE_NUM 1000
#define FEATURE_PER_INT (sizeof(int)*8/2)
#define FEATURE_IN_LAST_INT (FEATURE_NUM % FEATURE_PER_INT)
#define INT_PER_INSTANCE ((FEATURE_IN_LAST_INT>0)? (FEATURE_NUM / FEATURE_PER_INT) + 2 :(FEATURE_NUM / FEATURE_PER_INT) +1)
#define LABLE_OFFSET (INT_PER_INSTANCE - 1)
#define LAST_INT_DATA_OFFSET (INT_PER_INSTANCE - 2)
#define QUADRATICERANGE (FEATURE_NUM*(FEATURE_NUM-1)/2)

#define TRUE_INSTANCE_INDEX 0
#define TOTAL_INSTANCE_INDEX 1
#define DATA_OFFSET 2

class Constant
{
public:
	Constant();
};
#endif
